# Generated by Django 5.2.7 on 2025-11-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='title',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
