# Generated by Django 5.2.7 on 2025-11-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='title',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
