# Generated by Django 5.2.7 on 2025-11-07 14:27

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_music_description_music_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='cover',
            field=models.ImageField(null=True, upload_to=core.models.user_covers_path),
        ),
        migrations.AlterField(
            model_name='music',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='music',
            name='tune',
            field=models.FileField(upload_to=core.models.user_tunes_path),
        ),
    ]
