# Generated by Django 5.2.7 on 2025-11-08 18:48

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_music_cover_alter_music_owner_alter_music_tune'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('cover_album', models.ImageField(null=True, upload_to=core.models.user_covers_path)),
                ('name', models.TextField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='music',
            name='cover',
        ),
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.album'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(null=True, upload_to=core.models.user_icon_path)),
                ('description', models.TextField()),
                ('nickname', models.CharField(max_length=50)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.creator'),
        ),
    ]
