# Generated by Django 5.2.7 on 2025-11-11 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_album_remove_music_cover_music_album_creator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category_Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which_music', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.music')),
            ],
        ),
        migrations.CreateModel(
            name='Category_Bridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category_song')),
            ],
        ),
    ]
