# Generated by Django 5.2.7 on 2025-11-12 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_category_song_category_bridge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.creator'),
        ),
    ]
