# Generated by Django 5.2.7 on 2025-12-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_music_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='release',
            field=models.BooleanField(default=False),
        ),
    ]
